version: "3"
services:
  couchpotato:
    image: gitlab/gitlab-runner:alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 500M
    environment:
     - TZ=America/Chicago
