version: "3"
services:
  jenkins:
    image: jenkins/jenkins:lts
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 256M
    ports:
      - "8082:8080"
    environment:
     - PUID=1000
     - PGID=1000
    volumes:
      - "/app/config/jenkins:/var/jenkins_home"
    networks:
      - cicdnet
networks:
  cicdnet:
